config/routes.rb
Rails.application.routes.draw do

  # Not needed yet
  # devise_for :users
  root 'home#index'
  get 'contact', to: 'contacts#new'
  resources :services, only: [:index]
  resources :about, only: [:index]

  # Redirects routes to index if a wrong route is entered.
  get '*path' => redirect('/')

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController 
  def index 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    if params['email']
      ContactMailer.contact_email(params).deliver_now
      flash[:notice] = 'Message sent. Thank you!'
      redirect_to root_path
    end
  end

end 

app/controllers/home_controller.rb
class HomeController < ApplicationController
def index
end 
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController 

  def index 
  end

end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="content-wrapper-services">
    <div class="content">
        <div class="pure-g">
          <div class="pure-u-1-2">
              <h2>Contact Us</h2> 
            <p>Lorem ipsum dolor amet hella celiac meh, PBR&B 
              trust fund meggings XOXO intelligentsia paleo 
              </p>
          </div>
          <div class="pure-u-1-2">
            <form class="pure-form pure-form-stacked">
                <%= form_tag contact_path, authenticity_token: false do %>
                  <p>Name</p>
                  <%= text_field_tag :name %>
                  <p>Email</p>
                  <%= email_field_tag :email %>
                  <p>Message</p>
                  <%= text_field_tag :message %>
                  <%= submit_tag 'Send', class: 'pure-button' %>
                <% end %>
            </form>

          </div>
        </div>
    </div>
  </div>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tesla Fintech | Blockchain Consulting</title>
    <link rel="shortcut icon" href="/tesla_t.png" type="image/png">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
  <div class="header">
    <div class="home-menu pure-menu pure-menu-horizontal pure-menu-fixed">
        <a class="pure-menu-heading" href="/"><img src="/logo.png"></a>
          <% flash.each do |key, value| %>
            <div class="flash-message"><%= value %></div>
          <% end %>
        <ul class="pure-menu-list">
            <li class="pure-menu-item pure-menu-selected"><a href="#" class="pure-menu-link"></a></li>
            <li class="pure-menu-item"><a href="/services" class="pure-menu-link">Services</a></li>
            <li class="pure-menu-item"><a href="/about" class="pure-menu-link">About Us</a></li>
            <li class="pure-menu-item"><a href="/contact" class="pure-menu-link">Contact</a></li>
        </ul>
    </div>
  </div>

    <%= yield %>
    <div class="footer l-box is-center">
        &copy; Telsa Fintech 2017
    </div>
  </body>
</html>